# Generated by Django 2.2.8 on 2020-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_card_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='place',
            field=models.CharField(default='neuer test', max_length=200),
        ),
    ]
